env: prod

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ***REMOVED***
    url: jdbc:mysql://localhost:3306/common?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai

server:
  port: 8443
  ssl:
    key-store: classpath:certs/zilinn-wang-tomcat-0514140907.jks
    key-store-password: cptbtptp***REMOVED***
    keyStoreType: JKS
    keyAlias: 1

chatMongoDB:
  host: localhost
  port: 27017
  userName: ***REMOVED***
  authDB: admin
  password: ***REMOVED***


cardMongoDB:
  host: localhost
  port: 27017
  userName: ***REMOVED***
  authDB: admin
  password: ***REMOVED***

blogMongoDB:
  host: localhost
  port: 27017
  userName: ***REMOVED***
  authDB: admin
  password: ***REMOVED***

mqtt:
  url: ssl://localhost:8883
  clientId: prod-backend

jwt:
  secret: ***REMOVED***
  expiration: 1800