env: dev



spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ***REMOVED***
    url: jdbc:mysql://***REMOVED***:3306/common?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai


chatMongoDB:
  host: ***REMOVED***
  port: 27017
  userName: ***REMOVED***
  authDB: admin
  password: ***REMOVED***


cardMongoDB:
  host: ***REMOVED***
  port: 27017
  userName: ***REMOVED***
  authDB: admin
  password: ***REMOVED***

blogMongoDB:
  host: ***REMOVED***
  port: 27017
  userName: ***REMOVED***
  authDB: admin
  password: ***REMOVED***

mqtt:
  url: ssl://***REMOVED***:8883
  clientId: dev-backend

jwt:
  secret: ***REMOVED***
  expiration: 18000000

logging:
  level:
    org.springframework.web: DEBUG
