env: dev

server:
  port: 8443
  ssl:
    key-store: classpath:certs/https.p12
    key-store-password: ***REMOVED***
    keyStoreType: PKCS12
    keyAlias: tomcat

chatMongoDB:
  host: ***REMOVED***
  port: 27017
  userName: ***REMOVED***
  authDB: admin
  password: ***REMOVED***


cardMongoDB:
  host: ***REMOVED***
  port: 27017
  userName: ***REMOVED***
  authDB: admin
  password: ***REMOVED***

userMongoDB:
  host: ***REMOVED***
  port: 27017
  userName: ***REMOVED***
  authDB: admin
  password: ***REMOVED***

mqtt:
  url: ssl://***REMOVED***:8883
  clientId: dev-backend

jwt:
  secret: ***REMOVED***
  expiration: 1800


