env: prod

chatMongoDB:
  host: localhost
  port: 27017
  userName: ***REMOVED***
  authDB: admin
  password: ***REMOVED***


cardMongoDB:
  host: localhost
  port: 27017
  userName: ***REMOVED***
  authDB: admin
  password: ***REMOVED***

blogMongoDB:
  host: localhost
  port: 27017
  userName: ***REMOVED***
  authDB: admin
  password: ***REMOVED***

mqtt:
  url: ssl://localhost:8883
  clientId: prod-backend

jwt:
  secret: ***REMOVED***
  expiration: 1800