env: prod

server:
  port: 8443
  ssl:
    key-store: classpath:certs/https.p12
    key-store-password: ***REMOVED***
    keyStoreType: PKCS12
    keyAlias: tomcat

chatMongoDB:
  host: localhost
  port: 27017
  userName: ***REMOVED***
  authDB: admin
  password: ***REMOVED***


cardMongoDB:
  host: localhost
  port: 27017
  userName: ***REMOVED***
  authDB: admin
  password: ***REMOVED***

mqtt:
  url: ssl://localhost:8883
  clientId: prod-backend