mybatis-plus:
  type-aliases-package: com.***REMOVED***.site.model.blog
  mapper-locations: classpath:mapper/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    banner: false

server:
  port: 8443
  ssl:
    key-store: classpath:certs/https.p12
    key-store-password: ***REMOVED***
    keyStoreType: PKCS12
    keyAlias: tomcat