###
# sign in
POST https://{{host}}:8443/api/user/signIn
Content-Type: application/x-www-form-urlencoded

username=***REMOVED***&password=123456

###
# sign up
POST https://{{host}}:8443/api/user/signUp
Content-Type: application/x-www-form-urlencoded

username=***REMOVED***&password=123456

###
POST https://{{host}}:8443/api/user/info
Authorization:eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ3YW5nemlsaW4iLCJpYXQiOjE1ODkyOTYyNTcsImV4cCI6MTU4OTI5ODA1N30.rPZKxpWfvNxODWHfYgOtaQKr7y_pfq2Hy9V9-PsLqiWws4idHjRev8NN9g5mH8Vm6QftmWCKAoZnaMRJPP67sw
