###
# sign in
POST https://{{host}}:8443/api/user/signIn
Content-Type: application/x-www-form-urlencoded

username=wangzilin&password=123456

###
# sign up
POST https://{{host}}:8443/api/user/signUp
Content-Type: application/x-www-form-urlencoded

username=wangzilin&password=123456

###
POST https://{{host}}:8443/api/user/info
Authorization:eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ3YW5nemlsaW4iLCJpYXQiOjE1ODkzNTk2NTksImV4cCI6MTYwNzM1OTY1OX0.3CF1vFi51LwH7_D33ERSgaMqXYe_JnyHZBjKdHLIsnQ522y6agHgeBVkHiX4QUxUkZ1X3OMx-HLHbS2brnAbaw
